### ISSUE TITLE
Teemakaardikihi kujunduste kirjeldamine

### ISSUE THREAD

**Issue by tkardi** [e-gov/thema#4]
teemakaardi konfiguratsioon (#2) peab kaasama mingil kujul temaatilise kujunduse. 
punktid, jooned, polügonid.

**Comment by tormi** [comment]
teemakaardi konfiguratsioon on vist kandes #3 ;)

**Comment by tkardi** [comment]
vt d4a5afb

**Comment by tkardi** [comment]
punktobjekti kujundusparameetrid peaks sisaldama 
- kasutatav ikoon/leppemärk (valikuline, kui ei ole määratud võtame kaart/static/img/default-icon.png)
- kuvatava ikooni suurus (valikuline, kui ei ole määratud, siis kasutame mingit fikseeritud väärtust)
- kuvatava ikooni ankur (valikuline, kui ei ole määratud, siis paneme ikooni keskpaiga punkti kohale)

joonobjekti kujundusparameetrid võiks sisaldada
- joone värv
- joone paksus
- joone läbipasitvus
- *joone stiil (s.t svg dasharray)* ?

polügonide kujundusparameetrid võiks sisaldada
- piirjoone värv 
- piirjoone paksus
- piirjoone läbipaistvus
- sisu täitevärv
- sisu läbipaistvus
- *piirjoone stiil (s.t svg dasharray)* ?

**Comment by tkardi** [comment]
dasharray kasutamine kahheldatud vektoriga võib olla problemaatiline - kahhli piiride kohalt lähevad kriipsud katki :(. jätab selle praegu välja. 

Praegu on lahendatud tervele kihile sama kujunduse andmine `thema[n].style.type == default`. Vaja oleks lisaks nüüd teha atribuudipõhiselt, nt `thema[n].style.type == classify`.

**Comment by tkardi** [comment]
Muutsin "kohalikud ikoonid" svg peale, [develi eelvaates](http://htmlpreview.github.io/?https://github.com/e-gov/thema/blob/devel/kaart/thema/index.html) tundub, et neid ei näidata.

**Comment by tkardi** [comment]
vt 20f8470.
Lisaks: kujunduste [README](../tree/devel/kaart/thema/README.md) on lootusetult maha jäänud :(

**Comment by tkardi** [comment]
Algsel kujul olemas. Kui täiendusi/probleeme, siis avada uus õssu.
